steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$gcp-pipeline-450901/rumana-100989791/my-app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/rumana-100989791/my-app:$COMMIT_SHA']
options:
  logging: 'CLOUD_LOGGING_ONLY'
