steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/rumana-100989791/my-app:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/rumana-100989791/my-app:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/rumana-100989791/my-app:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service'
      - 'my-app'  # Explicitly define the service name

# Substitutions for dynamic values
substitutions:
  _REGION: "us-central1"

# Define IAM permissions for Cloud Run deployment
options:
  logging: CLOUD_LOGGING_ONLY

# Specify the images being built
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/rumana-100989791/my-app:$COMMIT_SHA'
