steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/gcp-pipeline-450901/rumana-100989791/my-app:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/gcp-pipeline-450901/rumana-100989791/my-app:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/gcp-pipeline-450901/rumana-100989791/my-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Substitutions for dynamic values
substitutions:
  _REGION: "us-central1"

# Define IAM permissions for Cloud Run deployment
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/gcp-pipeline-450901/rumana-100989791/my-app:$COMMIT_SHA'
